memor_ae_text_homepage:
    pattern:  /
    defaults: { _controller: MEMORAeTextBundle:Page:index }
    requirements:
        _method:  GET
        
memor_ae_text_homepage:
    pattern:  /{id}
    defaults: { _controller: MEMORAeTextBundle:Page:index }
    requirements:
        _method:  GET
        id: \d+