memorae_section:
    resource: "@MEMORAeTextBundle/Resources/config/routing/sectionentity.yml"
    prefix:   /administrer/section

memorae_media:
    resource: "@MEMORAeTextBundle/Resources/config/routing/mediaentity.yml"
    prefix:   /administrer/media

memorae_admin:
    resource: "@MEMORAeTextBundle/Resources/config/routing/adminPage.yml"
    prefix: /administrer
    
    
memorae_homepage:
    path: /{id}
    defaults: { _controller: MEMORAeTextBundle:Page:index, id: 1}
    requirements:
        _method:  GET
        id: \d*
        
memorae_homepage_avec_langue:
    path: /{_locale}/{id}
    defaults: { _controller: MEMORAeTextBundle:Page:index, id: 1}
    requirements:
        _method:  GET
        id: \d*
        _locale: fr|en