memor_ae_user:
    resource: "@MEMORAeUserBundle/Resources/config/routing.yml"
    prefix:   /

memor_ae_page:
    resource: "@MEMORAeTextBundle/Resources/config/routing.yml"
    
app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
